export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const MY_ORDERS_LIST_REQUEST = "MY_ORDERS_LIST_REQUEST";
export const MY_ORDERS_LIST_SUCCESS = "MY_ORDERS_LIST_SUCCESS";
export const MY_ORDERS_LIST_FAIL = "MY_ORDERS_LIST_FAIL";
export const MY_ORDERS_LIST_RESET = "MY_ORDERS_LIST_RESET";


export const PAYMENTS_LIST_REQUEST ="PAYMENTS_LIST_REQUEST";
export const PAYMENTS_LIST_SUCCESS ="PAYMENTS_LIST_SUCCESS";
export const PAYMENTS_LIST_FAIL ="PAYMENTS_LIST_FAIL";