export const products = [
  {
    id: 1,
    name: "Beauful product for your beauty enhancement",
    deccription:
      "In publishing and graphic design Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content Lorem ipsum may be used as a placeholder before final copy is available",
    image: "/images/1.jpg",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
  {
    id: 2,
    name: "Beauful product for your beauty enhancement",
    deccription:
      "In publishing and graphic design Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content Lorem ipsum may be used as a placeholder before final copy is available",
    image: "/images/2.png",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
  {
    id: 3,
    name: "Beauful product for your beauty enhancement",
    deccription:
      "In publishing and graphic design Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content Lorem ipsum may be used as a placeholder before final copy is available",
    image: "/images/3.jpeg",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
  {
    id: 4,
    name: "Beauful product for your beauty enhancement",
    deccription:
      "In publishing and graphic design Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content Lorem ipsum may be used as a placeholder before final copy is available",
    image: "/images/4.png",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
  {
    id: 5,
    name: "Beauful product for your beauty enhancement",
    deccription:
      "In publishing and graphic design Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content Lorem ipsum may be used as a placeholder before final copy is available",
    image: "/images/5.jpeg",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
  {
    id: 6,
    name: "Beauful product for your beauty enhancement",
    deccription:
      "In publishing and graphic design Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content Lorem ipsum may be used as a placeholder before final copy is available",
    image: "/images/6.jpg",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
  {
    id: 7,
    name: "Beauful product for your beauty enhancement",
    deccription:
      "In publishing and graphic design Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content Lorem ipsum may be used as a placeholder before final copy is available",
    image: "/images/7.jpeg",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },

  {
    id: 10,
    name: "Beauful product for your beauty enhancement",
    deccription:
      "In publishing and graphic design Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content Lorem ipsum may be used as a placeholder before final copy is available",
    image: "/images/10.jpg",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
  {
    id: 11,
    name: "Beauful product for your beauty enhancement",
    deccription:
      "In publishing and graphic design Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content Lorem ipsum may be used as a placeholder before final copy is available",
    image: "/images/11.jpg",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
  {
    id: 12,
    name: "Beauful product for your beauty enhancement",
    deccription:
      "In publishing and graphic design Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content Lorem ipsum may be used as a placeholder before final copy is available",
    image: "/images/12.jpeg",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
  {
    id: 13,
    name: "Beauful product for your beauty enhancement",
    deccription:
      "In publishing and graphic design Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content Lorem ipsum may be used as a placeholder before final copy is available",
    image: "/images/13.jpg",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
  {
    id: 14,
    name: "Beauful product for your beauty enhancement",
    deccription:
      "In publishing and graphic design Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content Lorem ipsum may be used as a placeholder before final copy is available",
    image: "/images/14.jpeg",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
  {
    id: 15,
    name: "Beauful product for your beauty enhancement",
    deccription:
      "In publishing and graphic design Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content Lorem ipsum may be used as a placeholder before final copy is available",
    image: "/images/15.jpg",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
  {
    id: 16,
    name: "Beauful product for your beauty enhancement",
    deccription:
      "In publishing and graphic design Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content Lorem ipsum may be used as a placeholder before final copy is available",
    image: "/images/16.jpeg",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
];

export const carouselItems = [
  {
    id: 1,
    name: "Beauful product for your beauty enhancement",
    deccription: "20% of all Make ups",
    image: "/images/carousel1.webp",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
  {
    id: 2,
    name: "Beauful product for your beauty enhancement",
    deccription: "Flash Sale of 30%",
    image: "/images/carousel2.webp",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
  {
    id: 3,
    name: "Beauful product for your beauty enhancement",
    deccription: "40% Off from 8-20 of May",
    image: "/images/carousel3.webp",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
  {
    id: 4,
    name: "Beauful product for your beauty enhancement",
    deccription: "On Bestsellers",
    image: "/images/carousel4.webp",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
  {
    id: 5,
    name: "Beauful product for your beauty enhancement",
    deccription: "50% Flash Sale",
    image: "/images/carousel5.webp",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
  {
    id: 6,
    name: "Beauful product for your beauty enhancement",
    deccription: "On Orders Over 400",
    image: "/images/carousel5.webp",
    brand: "Beautify",
    category: "Beauty",
    subCategory: "Men Beauty",
    price: 399.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 40,
  },
];

export const categoryList = [
  {
    id: 1,
    name: "Skin",
  },
  {
    id: 2,
    name: "Men",
  },
  {
    id: 3,
    name: "Women",
  },
  {
    id: 4,
    name: "Face",
  },
  {
    id: 5,
    name: "Make up",
  },
  {
    id: 6,
    name: "Appliances",
  },
  {
    id: 7,
    name: "Fragrance",
  },
  {
    id: 8,
    name: "Mom and Baby",
  },
  {
    id: 9,
    name: "Wellness",
  },
  {
    id: 10,
    name: "Hair",
  },
];
